version: "3.9"

services:

  #PHP Service
  app:
    build: .
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  #database
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beetroot_new
      MYSQL_USER: beetroot
      MYSQL_PASSWORD: beetroot
    restart: always
    container_name: mysql_beetroot
    networks:
      - app-network

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8008:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: "local"